export const POST_MILEAGE_USER_VENDOR= "POST_MILEAGE_USER_VENDOR";
export const LOAD_POST_MILEAGE = "LOAD_POST_MILEAGE";
export const SET_INIT_OR_END_MILEAGE = "SET_INIT_OR_END_MILEAGE";
export const SET_INIT_VISITDRIVER = "SET_INIT_VISITDRIVER"
export const SAVE_UUID_ROUTE_CUSTOMER = "SAVE_UUID_ROUTE_CUSTOMER"