export const SAVE_DOCUMENTS_TRACKING_ASIGNED = "SAVE_DOCUMENTS_TRACKING_ASIGNED"
export const SAVE_DOCUMENTS_TRACKING_ASIGNED2 = "SAVE_DOCUMENTS_TRACKING_ASIGNED2"
export const SAVE_DOCUMENTS_INROUTE  = "SAVE_DOCUMENTS_INROUTE"