export const GET_PRODUCTS_BY_COMPANY = "GET_PRODUCTS_BY_COMPANY"
export const SAVE_PRODUCT_FOR_VIEW = "SAVE_PRODUCT_FOR_VIEW"
export const SET_ITEM_CHANGE= "SET_ITEM_CHANGE"
export const SET_NEW_ITEM_CHANGE = "SET_NEW_ITEM_CHANGE"