export const GET_USER = "GET_USER";
export const LOAD_GET_USER = "LOAD_GET_USER";
export const LOGOUT_USER = "LOGOUT_USER"
export const SET_COORDS_ACTUALITY ="SET_COORDS_ACTUALITY"
export const SET_COORDS_DESTINATION = "SET_COORDS_DESTINATION"