export const LOAD_GET_CUSTOMERS_VENDOR  = "LOAD_GET_CUSTOMERS_VENDOR";
export const GET_CUSTOMER_VENDOR = "GET_CUSTOMER_VENDOR"
export const SET_CUSTOMER_SELECTED ="SET_CUSTOMER_SELECTED"
export const LOAD_SET_VISIT_CUSTOMER ="LOAD_SET_VISIT_CUSTOMER"